version: '3'
services:
  kiwix-serve:
    container_name: kiwix-serve
    image: kiwix/kiwix-serve
    volumes:
      - /share/CACHEDEV1_DATA/Kiwix/data:/data
    ports:
      - '5000:8080'
    command:
      wikipedia_en_all_maxi_2022-05.zim
      wikibooks_en_all_maxi_2021-03.zim
      wikiversity_en_all_maxi_2021-03.zim

  ##TODO: add Jellyfin