version: '3.3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    restart: always
    environment:
      - TZ=America/Denver
      - ESPHOME_DASHBOARD_USE_PING=true
    ports:
      - 6052:6052
      - 6123:6123
    volumes:
      - /share/CACHEDEV1_DATA/Container/esphome:/config
      - /etc/localtime:/etc/localtime:ro

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    network_mode: host
    privileged: true
    restart: always
    ports:
      - 8123:8123
    volumes:
      - /share/CACHEDEV1_DATA/Container/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Denver
      - DISABLE_JEMALLOC=true
      - JEMALLOC_DISABLE=true
      - PUID=1000
      - PGID=1000

  vscode:
    container_name: vscode
    image: linuxserver/code-server:3.12.0
    restart: always
    volumes:
      - '/share/CACHEDEV1_DATA/Container/vscode:/config'
      - '/share/CACHEDEV1_DATA/Container/homeassistant/:/homeassistant'
      - '/share/CACHEDEV1_DATA/Container/esphome/:/esphome'
    environment:
      - 'DOCKER_MODS=ghcr.io/aneisch/code-server-home-assistant'
      - 'HOMEASSISTANT_URL=http://127.0.0.1:8123'
      - PUID=1000
      - PGID=1000
      - HOMEASSISTANT_TOKEN=XXX
