default_config:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.182:3218/
    require_admin: true
mqtt:
  broker: http://192.168.1.182:1883

recorder:
  db_url: mysql://homeassistant:ha_dbdatabasepassword@192.168.1.182/ha_db?charset=utf8
  purge_keep_days: 30
