version: "3.8"
services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    ports:
      - 4000:80
    volumes:
      - /appdata/Dashy/conf.yml:/app/public/conf.yml
      - /appdata/Dashy/icons:/app/public/item-icons
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /appdata/Dokuwiki/config:/config
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped